---
title: "graphs"
format: html
---

```{r}
library(tidyverse)
```
# Data


## Paleo

### Zachos_2010

```{r}
isotopes <- read_tsv("../Data/Paleo/Zachos et al. 2010/208-1262_isotope.tab", skip = 20)
bulk_stable <- read_tsv("../Data/Paleo/Zachos et al. 2010/208-1262_bulk_stable_isotope.tab", skip = 23)
age_model <- read_tsv("../Data/Paleo/Zachos et al. 2010/207-1258_208-1262_age_model.tab", skip = 32)
zachos <- read_tsv("../Data/Paleo/Zachos et al. 2010/Zachos_2010.tab", skip = 23)
```


Bulk stable is what we want: `isotopes` extends to older ages, which we don't care about. `Zachos` is data only from Zachos, whereas `isotopes` also includes other papers.

```{r}
bulk_stable <- bulk_stable%>%
  mutate(delta_c_13 = `δ13C [‰ PDB]`,
         delta_o_18 = `δ18O [‰]`)

bulk_stable%>%
  # filter( `Age [ka BP]` > 55350 & `Age [ka BP]` < 55600)%>%
  ggplot(aes(x = `Age [ka BP]`, y = delta_c_13))+
  geom_line()+
  theme_minimal()

bulk_stable%>%
  ggplot(aes(x = `Age [ka BP]`, y = delta_o_18))+
  geom_line()+
  theme_minimal()

```

### Jiang et al

```{r}
library(readxl)
#Dataset1 sheets
bulk_carbonate <- read_excel("../Data/Paleo/Jiang et al/Dataset1.xlsx")
organic_hg <- read_excel("../Data/Paleo/Jiang et al/Dataset1.xlsx", sheet = "Bulk organic & Hg")
alkane_d13c <- read_excel("../Data/Paleo/Jiang et al/Dataset1.xlsx", sheet = "alkane d13C")
Apolar_biomarker <- read_excel("../Data/Paleo/Jiang et al/Dataset1.xlsx", sheet = "Apolar biomarker")
GDGT <- read_excel("../Data/Paleo/Jiang et al/Dataset1.xlsx", sheet = "GDGT data")
clumped_isotope <- read_excel("../Data/Paleo/Jiang et al/Dataset1.xlsx", sheet = "Clumped isotope")
#Dataset2 sheet
age_model <- read_excel("../Data/Paleo/Jiang et al/Dataset2.xlsx")
colnames(age_model)[3] <- "age_model_1"
colnames(age_model)[4] <- "age_model_2"
```

C13 and O18 carbonate over time

```{r}
bulk_carbonate_joined <- bulk_carbonate%>%
  left_join(age_model, by = join_by(`Sample NO.`))

bulk_carbonate_joined <- bulk_carbonate_joined%>%
  filter(!is.na(age_model_1))%>%
  select(`Sample NO.`,`Depth (m)`, age_model_1, `δ13Ccarb`, `δ18Ocarb`, Comment)

bulk_carbonate_joined%>%
  mutate(Comment2 = coalesce(Comment, "NoPhase")) %>% 
  ggplot(aes(x = age_model_1, y = δ18Ocarb, color = Comment2))+
  geom_point()+
  labs(title="δ18O during the POE and PETM", subtitle="Data from Jiang et al. 2025", x="kyr relative to onset of PETM", y="δ18O ‰", color="Phase") +
    scale_color_manual(
    values = c(
      "PETM" = "#0072B2",
      "PETM onset" = "#009E73",
      "POE" = "#E69F00",
      "NoPhase" = "darkgray"
    ),
    breaks = c("POE", "PETM onset", "PETM")) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold")) 

bulk_carbonate_joined%>%
  mutate(Comment2 = coalesce(Comment, "NoPhase")) %>% 
  ggplot(aes(x = age_model_1, y = δ13Ccarb, color = Comment2))+
  geom_point()+
    labs(title="δ13C during the POE and PETM", subtitle="Data from Jiang et al. 2025", x="kyr relative to onset of PETM", y="δ13C ‰", color="Phase") +
  scale_color_manual(
    values = c(
      "PETM" = "#0072B2",
      "PETM onset" = "#009E73",
      "POE" = "#E69F00",
      "NoPhase" = "darkgray"
    ),
    breaks = c("POE", "PETM onset", "PETM")) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold")) 
```

TOC%, Hg/TOC, CaCO3

```{r}
organic_hg <- organic_hg%>%
  mutate(`TOC%` = as.numeric(`TOC%`))

organic_hg_joined <- organic_hg%>%
  left_join(age_model, by = join_by(`Sample NO.`))

organic_hg_joined <- organic_hg_joined%>%
  filter(!is.na(age_model_1))%>%
  select(`Sample NO.`,`Depth (m)`, age_model_1, `wt.%CaCO3`, `TOC%`, `Hg (μg/kg, ppb)`, Comments)

organic_hg_joined%>%
  ggplot(aes(x = age_model_1, y = `wt.%CaCO3`, color = Comments))+
  geom_point()+
  theme_minimal()

organic_hg_joined%>%
  ggplot(aes(x = age_model_1, y = `TOC%`))+
  geom_line()+
  theme_minimal()
```


## Modern

```{r}
library(ncdf4)
temp_ocean <- read_csv("../Data/Modern/avg_temp_anomaly_ocean.csv", skip = 3)

temp_ocean <- temp_ocean%>%
  mutate(Date = str_c(str_extract(Date, "\\d{4}"), str_extract(Date, "(?<=\\d{4}).*"), sep = "-"),
         Date = ym(Date))

temp_land <- read_csv("../Data/Modern/avg_temp_anomaly_land.csv", skip = 3)

temp_land <- temp_land%>%
  mutate(Date = str_c(str_extract(Date, "\\d{4}"), str_extract(Date, "(?<=\\d{4}).*"), sep = "-"),
         Date = ym(Date))

co2 <- read_csv("../Data/Modern/monthly_in_situ_co2_mlo.csv", skip = 61) #Column 5 is what we want
monthly_O18 <- read_csv("../Data/Modern/monthly_flask_o18_mlo.csv", skip = 58) #Column 5 is what we want
monthly_C13 <- read_csv("../Data/Modern/monthly_flask_c13_mlo.csv", skip = 58) #Column 5 is what we want
sea_ice <- read_csv("../Data/Modern/N_09_extent_v4.0.csv")
```


# Viz

## Sea Ice over time

```{r}
sea_ice%>%
  ggplot(aes(x = year, y = extent))+
  geom_line()+
  theme_minimal()+
  labs(y = expression("Extent (million km"^2*")"), x = "Year", title = "Arctic Sea Ice Extent in September, 1979 to Present", subtitle = "data from Fetterer et al")+
  theme(plot.title = element_text(face = "bold"))
```


## Rate plot

### Modern

```{r}
#13C
monthly_C13 <- monthly_C13[-1:-2,]%>%
  mutate(delta_13_c = `13C...5`,
         numeric_date = Date...4)%>%
  select(Yr, Mn, numeric_date, delta_13_c)

monthly_C13_rate <- monthly_C13%>%
  filter(delta_13_c != "NaN")%>%
  mutate(delta_13_c = as.numeric(delta_13_c),
         monthly_rate_change = delta_13_c - lag(delta_13_c, 1))%>%
  mutate(date = as_date(date_decimal(numeric_date)))%>%
  group_by(Yr)%>%
  summarize(avg_c13 = mean(delta_13_c))%>%
  mutate(yearly_rate_change = avg_c13 - lag(avg_c13, 1))

monthly_C13_rate%>%
  ggplot(aes(x = Yr, y = avg_c13))+
  geom_point(color="red3")+
  theme_minimal() +
  labs(title="Modern Atmospheric δ13C since 1980", subtitle="Data from Mauna Loa Observatory, Hawaii", x="Year", y="δ13C ‰") +
  theme(plot.title = element_text(face = "bold")) 

#18O
monthly_O18 <- monthly_O18[-1:-2,]%>%
  mutate(delta_18_o = `18O...5`,
         numeric_date = Date...4)%>%
  select(Yr, Mn, numeric_date, delta_18_o)

monthly_O18_rate <- monthly_O18 %>%
  filter(delta_18_o != "NaN")%>%
  mutate(delta_18_o = as.numeric(delta_18_o),
         monthly_rate_change = delta_18_o - lag(delta_18_o, 1))%>%
  mutate(date = as_date(date_decimal(numeric_date)))%>%
  group_by(Yr)%>%
  summarize(avg_18O = mean(delta_18_o))%>%
  mutate(yearly_rate_change = avg_18O - lag(avg_18O, 1))

monthly_O18_rate%>%
  ggplot(aes(x = Yr, y = avg_18O))+
  geom_point()+
  theme_minimal()
```


```{r}
monthly_C13 <- monthly_C13[-1:-2,]%>%
  mutate(delta_13_c = `13C...5`,
         numeric_date = Date...4)%>%
  select(Yr, Mn, numeric_date, delta_13_c)

monthly_C13_rate <- monthly_C13%>%
  filter(delta_13_c != "NaN")%>%
  mutate(delta_13_c = as.numeric(delta_13_c),
         monthly_rate_change = delta_13_c - lag(delta_13_c, 1))%>%
  mutate(date = as_date(date_decimal(numeric_date)))%>%
  group_by(Yr)%>%
  summarize(avg_c13 = mean(delta_13_c))%>%
  mutate(yearly_rate_change = avg_c13 - lag(avg_c13, 1))

modern_model <- lm(avg_c13 ~ Yr, data = monthly_C13_rate)

regression_modern <- monthly_C13_rate%>%
  mutate(predicted_c13 = fitted(modern_model))

slope_modern <- round(coef(modern_model)[2], 3)

monthly_C13_rate%>%
  ggplot(aes(x = Yr, y = avg_c13))+
  geom_point()+
  geom_line(aes(x = Yr, y = predicted_c13), data = regression_modern)+
  annotate("text",
           x = 2005,
           y = -7.8,
           label = str_c("rate = ", slope_modern, "‰/yr"),
           size = 4,
           fontface = "bold")+
  theme_minimal()+
  labs(title="δ13C from 1980 to Present", subtitle="Data from Mauna Loa Observatory, Hawaii", x="Year", y="δ13C ‰")+
  theme(plot.title = element_text(face = "bold")) 

```

### POE

```{r}
bulk_carbonate_joined_POE <- bulk_carbonate_joined[7:37, ]

bulk_carbonate_joined_POE%>%
  ggplot(aes(x = age_model_1, y = δ13Ccarb, color = Comment))+
  geom_point()+
  theme_minimal()

regression_POE <- bulk_carbonate_joined_POE[8:21, ]

poe_model <- lm(δ13Ccarb ~ age_model_1, data = regression_POE)

regression_POE <- regression_POE%>%
  mutate(predicted_c13 = fitted(poe_model))

slope_poe <- round(coef(poe_model)[2], 3)

bulk_carbonate_joined_POE%>%
  mutate(Comment2 = coalesce(Comment, "NoPhase"))%>%
  ggplot(aes(x = age_model_1, y = δ13Ccarb, color = Comment2))+
  geom_point(size = 2)+
  geom_line(aes(x = age_model_1, y = predicted_c13), data = regression_POE, color = "#E69F00", linewidth = 1.35)+
  annotate("text",
           x = -130,
           y = 1.2,
           label = str_c("rate = ", format(slope_poe/1000, scientific = FALSE), "‰/yr"),
           size = 4,
           fontface = "bold")+
  theme_minimal()+
  labs(title="δ13C during the POE", subtitle="Data from Jiang et al. 2025", x="kyr relative to onset of PETM", y="δ13C ‰", color="Phase") +
  scale_color_manual(
    values = c(
      "POE" = "#E69F00",
      "NoPhase" = "darkgray"
    ),
    breaks = c("POE")) +
    theme(plot.title = element_text(face = "bold")) 

comparison_petm_poe <- slope_poe/(slope_PETM)

```

### PETM

```{r}
bulk_carbonate_joined%>%
  filter(Comment == "PETM" | Comment == "PETM onset")%>%
  ggplot(aes(x = age_model_1, y = δ13Ccarb, color = Comment))+
  geom_point()+
  theme_minimal()

bulk_carbonate_joined_PETM <- bulk_carbonate_joined[91:213, ]

regression_PETM <- bulk_carbonate_joined_PETM[12:91, ]

PETM_model <- lm(δ13Ccarb ~ age_model_1, data = regression_PETM)

regression_PETM <- regression_PETM%>%
  mutate(predicted_c13 = predict(PETM_model, newdata = regression_PETM))

slope_PETM <- round(coef(PETM_model)[2], 3)

bulk_carbonate_joined_PETM%>%
  mutate(Comment2 = coalesce(Comment, "NoPhase"))%>%
  ggplot(aes(x = age_model_1, y = δ13Ccarb, color = Comment2))+
  geom_point(size = 2)+
  geom_line(aes(x = age_model_1, y = predicted_c13), data = regression_PETM, color = "#0072B2", linewidth = 1.35)+
  annotate("text",
           x = 70,
           y = -1.75,
           label = str_c("rate = ", format(slope_PETM/1000, scientific = FALSE), "‰/yr"),
           size = 4,
           fontface = "bold")+
  theme_minimal()+
  labs(title="δ13C during the PETM", subtitle="Data from Jiang et al. 2025", x="kyr relative to onset of PETM", y="δ13C ‰", color="Phase") +
  scale_color_manual(
    values = c(
      "PETM" = "#0072B2",
      "PETM onset" = "#009E73",
      "NoPhase" = "darkgray"
    ),
    breaks = c("PETM onset", "PETM")) +
    theme(plot.title = element_text(face = "bold")) 

```

